### ISSUE TITLE
No Scrollbar in website's left sidebar menu

### ISSUE THREAD

**Issue by devbapidey** [mvdnbrk/laravel-mix.com#30]
No Scrollbar in https://laravel-mix.com/docs/5.0 website's left sidebar menu

**Comment by mvdnbrk** [comment]
Please provide some more information such as OS, browser etc.

**Comment by geekish** [comment]
Having the same problem. Chrome 87 on macOS.

**Comment by mvdnbrk** [comment]
I don't see the need for a scrollbar if you can scroll the whole page.

**Comment by geekish** [comment]
The whole page scrolls but the menu is fixed so it gets cut off.

<img width="478" alt="Screen Shot 2020-12-25 at 12 42 30 PM" src="https://user-images.githubusercontent.com/684339/103140651-c4816400-46ae-11eb-9d8c-7749f8ca46f0.png">

That's all I can see on every single page.

**Comment by mvdnbrk** [comment]
I see, seems to happen on smaller screens. Will re-open this issue and take a look as soon as I can.
